# TensorFlow Basics

In [14]:
import tensorflow as tf

In [15]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors

In [16]:
hello = tf.constant('Hello')

In [17]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [18]:
world = tf.constant('World')

In [19]:
result = hello + world

In [20]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [21]:
type(result)

tensorflow.python.framework.ops.Tensor

In [22]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [23]:
result

b'HelloWorld'

** Computations **

In [24]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [25]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [26]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [27]:
sess

In [28]:
sess.close()

## Operations

In [29]:
const = tf.constant(10)

In [30]:
fill_mat = tf.fill((4,4),10)

In [31]:
myzeros = tf.zeros((4,4))

In [32]:
myones = tf.ones((4,4))

In [33]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [34]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [35]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [36]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [37]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.64336658  0.94249415  0.29980332  0.47034332]
 [ 0.03066172 -0.73474836  0.28406763 -0.11069401]
 [-0.06897704 -0.40521055  0.0933967  -0.80061722]
 [ 0.3863776   0.08505257  0.69271237 -1.00098622]]


[[ 0.62296021  0.69908917  0.79503417  0.05163407]
 [ 0.51357985  0.87031972  0.90585017  0.72802651]
 [ 0.12860131  0.81290472  0.34358096  0.40888929]
 [ 0.86461639  0.54258287  0.3866713   0.96334255]]




## Matrix Multiplication

In [38]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [39]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [40]:
b = tf.constant([[10],[100]])

In [41]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [42]:
result = tf.matmul(a,b)

In [43]:
result.eval()

array([[210],
       [430]], dtype=int32)