### TO LEARN
- dot product/ matrix multiplication /  inner product
- np.dot
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). [link](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication)

### Info
1. [np.cov](https://numpy.org/doc/stable/reference/generated/numpy.cov.html)
2. [covariance matrix](https://www.itl.nist.gov/div898/handbook/pmc/section5/pmc541.htm)
3. [TO READ, covariance, cross-covariance, auto-/cross-correliation and power spectrum density](https://stats.stackexchange.com/questions/49901/intuitive-understanding-covariance-cross-covariance-auto-cross-correliation-a)

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
X = np.array([[4.0,2.0,0.60],
               [4.2,2.1,0.59],
               [3.9,2.0,0.58],
               [4.3,2.1,0.62],
               [4.1,2.2,0.63]])
# X = np.array([[0, 2], [1, 1], [2, 0]])

In [3]:
X_=np.mean(X, axis=0)
X_

array([4.1  , 2.08 , 0.604])

In [4]:
diff = (X-X_)
diff

array([[-0.1  , -0.08 , -0.004],
       [ 0.1  ,  0.02 , -0.014],
       [-0.2  , -0.08 , -0.024],
       [ 0.2  ,  0.02 ,  0.016],
       [ 0.   ,  0.12 ,  0.026]])

### Same formular for variance-covariance matrix (or covariance matrix) and np.cov

![image.png](./imgs/covariance.png)

From the formular the ij are the opposite so need to switch the transpose

In [5]:
np.dot(diff.T, diff)/(X.shape[0]-1)

array([[0.025  , 0.0075 , 0.00175],
       [0.0075 , 0.007  , 0.00135],
       [0.00175, 0.00135, 0.00043]])

In [6]:
np.cov(X.T)

array([[0.025  , 0.0075 , 0.00175],
       [0.0075 , 0.007  , 0.00135],
       [0.00175, 0.00135, 0.00043]])