In [2]:
%reload_ext autoreload
%autoreload 2
import torch
import torch.nn.functional as F 
import random
import numpy as np
from EXITrl.helpers import print_weight_size, copy_params, update_params, ExperienceReplay, convert_to_tensor
import gym

### Experience Replay

In [25]:
memory = ExperienceReplay(3, 3)
memory.remember([1,10],2,3,False)
memory.remember([11,110],22,33, True)
memory.remember([111,1110],222,333, False)
memory.remember([1111,11110],2222,3333, True)
a, b, c, d = memory.recall()
a, b, c, d

(tensor([[   11.,   110.],
         [  111.,  1110.],
         [ 1111., 11110.]]),
 tensor([  22.,  222., 2222.]),
 tensor([  33.,  333., 3333.]),
 tensor([1., 0., 1.]))

### Prioritized Experience Replay
https://github.com/rlcode/per<br>
[medium](https://medium.freecodecamp.org/improvements-in-deep-q-learning-dueling-double-dqn-prioritized-experience-replay-and-fixed-58b130cc5682#8dd3)<br>
[paper](https://arxiv.org/pdf/1511.05952.pdf)

In [15]:
i = 0
T = torch.tensor([1,2,3,4,5])
T = torch.cat([T[0:i], T[i+1:]])
T[i:]

tensor([2, 3, 4, 5])