In [1]:
%reload_ext autoreload
%autoreload 2
import torch
import torch.nn.functional as F 
import random
import numpy as np
from EXITrl.helpers import print_weight_size, copy_params, update_params, ExperienceReplay, convert_to_tensor
import gym

### Experience Replay

In [13]:
memory = ExperienceReplay(2)
memory.remember([1,10],2,3,False)
memory.remember([11,110],22,33, True)
memory.remember([111,1110],222,333, False)
memory.remember([1111,11110],2222,3333, True)
a, b, c, d = memory.recall(2)
a, b, c, d

(tensor([[  11.,  110.],
         [ 111., 1110.]]),
 tensor([ 22., 222.]),
 tensor([ 33., 333.]),
 tensor([1., 0.]))