In [7]:
import numpy as np

### Min Max

In [3]:
a = np.array([1,2,3,4])
print(a.min())
print(a.max())
a

1
4


array([1, 2, 3, 4])

### Transpose

In [28]:
X = np.array([[[1,2,3],[4,5,6]]] )
print(X)
print(X.shape)
print('------------')
print(X.transpose())
print(X.transpose().shape)
print('------------')
print(X.transpose(0,2,1)) 
# 1. direction 0 same
# 2. move direction 2 to direction 1
# 3. move direction 1 to direction 2
print(X.transpose(0,2,1).shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
------------
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]]
(3, 2, 1)
------------
[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


### Miscellaneous

In [11]:
A = np.array([[1,2,3], [4,5,6]])
print(A.shape)
print(A.max())
print(A.min())
print(A.flatten())
print(A.reshape(-1,2))
print(np.arange(start=10, stop=20))
print(np.linspace(start=10, stop=20, num =4))
print(np.where(A%2==0))

(2, 3)
6
1
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[10 11 12 13 14 15 16 17 18 19]
[10.         13.33333333 16.66666667 20.        ]
(array([0, 1, 1]), array([1, 0, 2]))


### Apply if to batch

In [3]:
a = np.array([[0,1],[2,3]])
np.where(a>2, a, a+10)

array([[10, 11],
       [12,  3]])