In [2]:
import numpy as np

### Min Max

In [3]:
a = np.array([1,2,3,4])
print(a.min())
print(a.max())
a

1
4


array([1, 2, 3, 4])

### Transpose

In [28]:
X = np.array([[[1,2,3],[4,5,6]]] )
print(X)
print(X.shape)
print('------------')
print(X.transpose())
print(X.transpose().shape)
print('------------')
print(X.transpose(0,2,1)) 
# 1. direction 0 same
# 2. move direction 2 to direction 1
# 3. move direction 1 to direction 2
print(X.transpose(0,2,1).shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
------------
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]]
(3, 2, 1)
------------
[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


### Miscellaneous

In [11]:
A = np.array([[1,2,3], [4,5,6]])
print(A.shape)
print(A.max())
print(A.min())
print(A.flatten())
print(A.reshape(-1,2))
print(np.arange(start=10, stop=20))
print(np.linspace(start=10, stop=20, num =4))
print(np.where(A%2==0))

(2, 3)
6
1
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[10 11 12 13 14 15 16 17 18 19]
[10.         13.33333333 16.66666667 20.        ]
(array([0, 1, 1]), array([1, 0, 2]))


### Apply if to batch

In [3]:
a = np.array([[0,1],[2,3]])
np.where(a>2, a, a+10)

array([[10, 11],
       [12,  3]])

### vstack 
merge first axis
### hstack 
merge second axis

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[1],[3]])
np.hstack([a,b])

array([[1, 2, 1],
       [3, 4, 3]])

### dstack
merge third axis

In [11]:
a = np.array([[[1,2],[3,4]]])
b = np.array([[[1],[3]]])
np.dstack([a,b])

array([[[1, 2, 1],
        [3, 4, 3]]])

### append (push) [python not np]

In [3]:
arr = []
arr.append([1,2,3])
arr.append([4,5,6])

np.array(arr).shape

(2, 3)

### Unique

In [2]:
unique_label, unique_reverse, unique_count = np.unique(
    np.array([1,2,3,1,2,2]), return_inverse=True, return_counts=True)

### One Hot Algorithm

In [2]:
import numpy as np
def one_hot(data, num_class):
    num_data = len(data)
    hot = np.zeros((num_data, num_class))
    hot[range(num_data), data]=1
    return hot
one_hot([1,2,3],4)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### np.add.at
```python
a = np.zeros((3,3))
i = [2,0,2] # indices in axis 0
j = [1,2,1] # indices in axis 1
a[i,j] += 1
```
output:
```python
array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 2., 0.]])
```

In [4]:
a = np.zeros((3,3))
i = [2,0,2] # indices in axis 0
j = [1,2,1] # indices in axis 1
np.add.at(a, (i,j), 1)
a

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 2., 0.]])

In [158]:
from numpy import argmax
# define input string
data = 'hello world'
print('data : ',data)

# define universe of possible input values
alphabet = 'abcdefghijklmnopqrstuvwxyz '

# define a mapping of chars to integers
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

# integer encode input data
integer_encoded = [char_to_int[char] for char in data]
print('integer_encoded : ',integer_encoded)

# one hot encode
onehot_encoded = list()
for value in integer_encoded:
    letter = [0 for _ in range(len(alphabet))] # np.zeros()
    letter[value] = 1
    onehot_encoded.append(letter)
print('onehot_encoded : ',onehot_encoded)

# invert encoding
inverted = int_to_char[argmax(onehot_encoded[0])]
print('inverted : ',inverted)

data :  hello world
integer_encoded :  [7, 4, 11, 11, 14, 26, 22, 14, 17, 11, 3]
onehot_encoded :  [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

### Cast np.array Object dtype

In [18]:
arr = np.array([['one', [1, 2, 3]],['two', [4, 5, 6]]], dtype=np.object)
arr[:,1].astype(np.float)

ValueError: setting an array element with a sequence.

In [16]:
np.array(list(arr[:,1]), dtype=np.float).dtype

dtype('float64')

In [17]:
np.vstack(arr[:,1]).astype(np.float)

array([[1., 2., 3.],
       [4., 5., 6.]])