In [100]:
import tensorflow as tf
import numpy as np
import torch

In [150]:
a = tf.Variable([[[1, 2, 3]], [[4, 5, 6]]], shape=[2, 1, 3])
b = tf.Variable([[[1], [2], [3]], [[4], [5], [6]]], shape=[2, 3, 1])
a*b

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9]],

       [[16, 20, 24],
        [20, 25, 30],
        [24, 30, 36]]])>

### Outer Product

In [148]:
a = tf.reshape( tf.Variable([[[1,2,3]], [[4,5,6]]]), [2,1,3])
b = tf.transpose(a, perm=[0,2,1])

In [159]:
raw_a = tf.Variable([[1, 2, 3], [4, 5, 6]], shape=[2, 3])
raw_b = tf.Variable([[1, 2, 3,4], [4, 5, 6,7]], shape=[2, 4])
a = tf.expand_dims(raw_a, axis=1)
b = tf.expand_dims(raw_b, axis=1)
b = tf.transpose(b, perm=[0,2,1])
a*b

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9],
        [ 4,  8, 12]],

       [[16, 20, 24],
        [20, 25, 30],
        [24, 30, 36],
        [28, 35, 42]]])>