In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
%matplotlib notebook
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

In [2]:
w,h=10,10
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

### Utils

In [3]:
def delete_index(T, index=None):
    if index is None:
        return T
    elif index is -1:
        return T[:index]
    else:
        return torch.cat([T[:index], T[index+1:]])
delete_index(torch.arange(30).reshape(3,10), 1), \
delete_index(torch.arange(30).reshape(3,10)), \
delete_index(torch.arange(30).reshape(3,10), -1)

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]))

In [4]:
def delete_indexes(T, indexes=None):
    if indexes is None:
        return T
    else:
        if indexes[0] > indexes[1]: # ex indexes = [0, -1]
            return T
        elif indexes[1] == -1: # ex indexes = [-3, -1]
            return T[:indexes[0]]
        return torch.cat([T[:indexes[0]], T[indexes[1]+1:]])
arr = torch.arange(15).reshape(5,3)
arr, delete_indexes(arr, [0,2])

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]),
 tensor([[ 9, 10, 11],
         [12, 13, 14]]))

In [5]:
def fifo(current_arr, arr):
    current_arr = torch.unsqueeze(current_arr, 0)
    arr = delete_index(arr, index=0)
    return torch.cat((arr, current_arr))
fifo(torch.arange(10), torch.zeros(30).reshape(3,10))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [6]:
def push(arr, current_arr):
    if arr is None:
        return torch.unsqueeze(current_arr, 0)
    current_arr = torch.unsqueeze(current_arr, 0)
    return torch.cat((arr, current_arr))
push(torch.zeros(10).reshape(1,10), torch.arange(10)), push(None, torch.arange(10))

(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [7]:
def jump_bound(position):
    if position[0] >= w:
        position[0] = position[0] - w
    elif position[0] < 0:
        position[0] = w + position[0]
    if position[1] >= h:
        position[1] = position[1] - w
    elif position[1] < 0:
        position[1] = h + position[1]
    return position
jump_bound([10, -1])

[0, 9]

### Env

In [8]:
class MomentumObject:
    def __init__(self, w, h, device):
        self.w, self.h = w,h
        self._position = torch.zeros((2), dtype=torch.int).to(device)
        self._speed =  torch.zeros((2), dtype=torch.int).to(device)
    
    @property
    def position(self):
        return torch.clone(self._position)
    @property
    def speed(self):
        return torch.clone(self._speed)
    @speed.setter
    def speed(self, speed):
        self._speed = speed
    def step(self):
        self._position += self._speed
        jump_bound(self._position)
    def render(self, predict_position=None):
        state = torch.zeros((w,h))
        state[self._position[0], self._position[1]] = 1
        if predict_position is not None:
            predict_position = predict_position.type(torch.int)
            state[predict_position[0], predict_position[1]] = 0.2
        return state
momentum_object = MomentumObject(w, h, device)
momentum_object.step()
momentum_object.render()

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Add to Buffer

In [62]:
class MemoryReplay:
    def __init__(self, num_step_per_action, num_action_buffer, num_state, num_action, env):
        self.num_step_per_action = num_step_per_action
        self.num_action_buffer = num_action_buffer
        self.env = env
        self._states_actions = torch.zeros((num_step_per_action*num_action_buffer, num_state+num_action), dtype=torch.double).to(device)
        self.current_step = -1
        self._num_buffer = self.num_step_per_action * self.num_action_buffer
    def step(self):
        self.current_step += 1
        if self.current_step >= num_step_per_action:
            self.current_step = 0
        self.env.step()
        if self.current_step % self.num_step_per_action == 0:
            self.env.speed = torch.randint(-2, 2, size=(2,), device=device)
        state_action = torch.cat((self.env.position, self.env.speed))
        self._states_actions = fifo(state_action, self._states_actions)
    @property
    def states_actions(self):
        return torch.clone(self._states_actions)
    def warmup(self):
        for _ in range(self._num_buffer):
            self.step()
num_step_per_action = 4
num_action_buffer = 3
memory = MemoryReplay(num_step_per_action=num_step_per_action, 
                      num_action_buffer=num_action_buffer, 
                      num_state=2, 
                      num_action=2, 
                      env=momentum_object)
memory.warmup()

In [63]:
memory.step()
memory.step()
memory.states_actions, memory.current_step

(tensor([[ 8.,  5., -1., -1.],
         [ 7.,  4., -1., -1.],
         [ 6.,  3., -1., -2.],
         [ 5.,  1., -1., -2.],
         [ 4.,  9., -1., -2.],
         [ 3.,  7., -1., -2.],
         [ 2.,  5., -2.,  1.],
         [ 0.,  6., -2.,  1.],
         [ 8.,  7., -2.,  1.],
         [ 6.,  8., -2.,  1.],
         [ 4.,  9.,  0., -1.],
         [ 4.,  8.,  0., -1.]], device='cuda:0', dtype=torch.float64),
 1)

##### Find index shift (after add repeated indexes), from "START" or "END"

In [64]:
def get_index_shift(shift, from_start):
    if from_start:
        return shift*num_step_per_action - torch.sum(torch.arange(shift))
    else:
        return torch.sum(torch.arange(shift+1))
get_index_shift(1, True), get_index_shift(2, True), get_index_shift(1, False), get_index_shift(3, False)

(tensor(4), tensor(7), tensor(1), tensor(6))

##### Map direct indexes to repeated indexes

In [122]:
def map_increase_indexes(action_group_id, increment_index):
    x = torch.arange(num_step_per_action)
    repeats = torch.flip(x, dims=(0,)) + 1
    current_indexes = torch.repeat_interleave(x, repeats=repeats, dim=0)
    if increment_index:
        current_indexes += (action_group_id*num_step_per_action)
    return current_indexes
map_increase_indexes(0, True), map_increase_indexes(1, True)

(tensor([0, 0, 0, 0, 1, 1, 1, 2, 2, 3]),
 tensor([4, 4, 4, 4, 5, 5, 5, 6, 6, 7]))

In [121]:
[torch.arange(i) for i in range(num_step_per_action, 0, -1)]

[tensor([0, 1, 2, 3]), tensor([0, 1, 2]), tensor([0, 1]), tensor([0])]

In [123]:
def get_target_index(increment_index=True):
    # calculate shift after repeat target
    shift_start = (memory.current_step+1)%num_step_per_action
    shift_end = num_step_per_action - shift_start
    start_index = get_index_shift(shift_start, True)
    end_index = get_index_shift(shift_end, False)
    
    # repeat target indexes
    current_indexes = [map_indexes(i, increment_index) for _, i in enumerate(range(num_action_buffer + 1))]
    current_indexes = torch.cat(current_indexes).to(device)
#     current_indexes_raw = current_indexes
    current_indexes = delete_indexes(current_indexes, [0, start_index-1])
    current_indexes = delete_indexes(current_indexes, [-end_index, -1])
    return current_indexes-shift_start
current_indexes = get_target_index()
current_indexes

tensor([ 0,  1,  1,  1,  1,  2,  2,  2,  3,  3,  4,  5,  5,  5,  5,  6,  6,  6,
         7,  7,  8,  9,  9,  9,  9, 10, 10, 10, 11, 11], device='cuda:0')

In [124]:
def get_repeat_target_state(state):
    current_indexes = get_target_index(increment_index=True)
    return torch.index_select(state, dim=0, index=current_indexes)
target_states = get_repeat_target_state(memory.states_actions[:,:2])
target_states

tensor([[3., 6.],
        [2., 7.],
        [2., 7.],
        [2., 7.],
        [2., 7.],
        [1., 7.],
        [1., 7.],
        [1., 7.],
        [0., 7.],
        [0., 7.],
        [9., 7.],
        [8., 7.],
        [8., 7.],
        [8., 7.],
        [8., 7.],
        [9., 8.],
        [9., 8.],
        [9., 8.],
        [0., 9.],
        [0., 9.],
        [1., 0.],
        [2., 1.],
        [2., 1.],
        [2., 1.],
        [2., 1.],
        [3., 1.],
        [3., 1.],
        [3., 1.],
        [4., 1.],
        [4., 1.]], device='cuda:0', dtype=torch.float64)

In [125]:
def get_repeat_target_state_with_delta_time(state):
    state = get_repeat_target_state(state)
    delta_time = get_target_index(increment_index=False)
    delta_time = torch.unsqueeze(delta_time, 1)
    return torch.cat((state, delta_time), dim=1)
get_repeat_target_state_with_delta_time(memory.states_actions), memory.states_actions.shape

(tensor([[ 3.,  6., -1.,  1.,  0.],
         [ 2.,  7., -1.,  0., -3.],
         [ 2.,  7., -1.,  0., -3.],
         [ 2.,  7., -1.,  0., -3.],
         [ 2.,  7., -1.,  0., -3.],
         [ 1.,  7., -1.,  0., -2.],
         [ 1.,  7., -1.,  0., -2.],
         [ 1.,  7., -1.,  0., -2.],
         [ 0.,  7., -1.,  0., -1.],
         [ 0.,  7., -1.,  0., -1.],
         [ 9.,  7., -1.,  0.,  0.],
         [ 8.,  7.,  1.,  1., -3.],
         [ 8.,  7.,  1.,  1., -3.],
         [ 8.,  7.,  1.,  1., -3.],
         [ 8.,  7.,  1.,  1., -3.],
         [ 9.,  8.,  1.,  1., -2.],
         [ 9.,  8.,  1.,  1., -2.],
         [ 9.,  8.,  1.,  1., -2.],
         [ 0.,  9.,  1.,  1., -1.],
         [ 0.,  9.,  1.,  1., -1.],
         [ 1.,  0.,  1.,  1.,  0.],
         [ 2.,  1.,  1.,  0., -3.],
         [ 2.,  1.,  1.,  0., -3.],
         [ 2.,  1.,  1.,  0., -3.],
         [ 2.,  1.,  1.,  0., -3.],
         [ 3.,  1.,  1.,  0., -2.],
         [ 3.,  1.,  1.,  0., -2.],
         [ 3.,  1.,  1.,  0.

### SD + Normalize function

In [69]:
def standardize_state(state):
    ''' 
    state: [0, 9], [0, 9], action1, action2
    return: [-4.5, 4.5], [-4.5, 4.5], action1, action2
    '''
    state = torch.clone(state)
    state[:, 0] = state[:, 0] - ((w-1)/2)
    state[:, 1] = state[:, 1] - ((h-1)/2)
    return state
def normalize_state(state):
    ''' 
    state: [0, 9], [0, 9]
    return [0, 1], [0, 1] 
    '''
    state = torch.clone(state)
    state[:, 0] = (state[:, 0] + 0.5) / w
    state[:, 1] = (state[:, 1] + 0.5) / h
    return state
def denormalize_state(state):
    ''' 
    state: [0, 1], [0, 1] 
    return [0, 9], [0, 9]
    '''
    state = torch.clone(state)
    state[:, 0] = state[:, 0]*w -0.5
    state[:, 1] = state[:, 1]*h -0.5
    return state
a = denormalize_state(torch.tensor([[0.,1.]]))
a, torch.round(a)
# normalize_state(torch.tensor([[0.,9.]]))

(tensor([[-0.5000,  9.5000]]), tensor([[-0., 10.]]))

### Train

In [ ]:
def train(i):
    memory.step()
    encoder.train()
    optimizer.zero_grad()
    current_state = standardize_state(memory.states_actions)
    predict_state = encoder(current_state)
    
    state_prediction_feature = get_repeat_target_state_with_delta_time(predict_state)
    state_prediction = decoder(state_prediction_feature)
    
    future_label = normalize_state(memory.states_actions[:,:2])
    future_label = get_repeat_target_state(future_label)
    loss = mse_loss(state_prediction, future_label)
    loss.mean().backward(retain_graph=True)
    
    state_prediction = torch.round(denormalize_state(state_prediction))
    miss_distance = (future_label - state_prediction).float().sum().cpu().detach().numpy()
    print("loss[", i,"]:", loss.mean().cpu().detach().numpy(), 'miss_distance', miss_distance)
    
    loss.mean().backward()
    optimizer.step()
    
torch.manual_seed(1)
encoder = nn.Sequential(
                nn.Linear(4,16),
                nn.ReLU(),
                nn.Linear(16,32),
                nn.ReLU(),
                nn.Linear(32,8),
                nn.ReLU(),
                nn.Linear(8,8),
                nn.Sigmoid()).to(device).to(torch.float64)
decoder = nn.Sequential(
                nn.Linear(9,16),
                nn.ReLU(),
                nn.Linear(16,32),
                nn.ReLU(),
                nn.Linear(32,8),
                nn.ReLU(),
                nn.Linear(8,2),
                nn.Sigmoid()).to(device).to(torch.float64)

optimizer = optim.Adam(list(encoder.parameters()) + list(decoder.parameters()), lr=0.001)
mse_loss = nn.MSELoss(reduction='none')

lowest_loss_index = None
for i in range(5000):
    lowest_loss_index = train(i)

loss[ 0 ]: 0.1027811355762795 miss_distance -211.0
loss[ 1 ]: 0.10489019228652034 miss_distance -211.79999
loss[ 2 ]: 0.10206551540851362 miss_distance -212.7
loss[ 3 ]: 0.09916612556331074 miss_distance -213.5
loss[ 4 ]: 0.09887737083488976 miss_distance -214.99998
loss[ 5 ]: 0.10104762057390775 miss_distance -217.4
loss[ 6 ]: 0.09647392600108298 miss_distance -219.2
loss[ 7 ]: 0.08886055939098303 miss_distance -220.4
loss[ 8 ]: 0.08618215909283311 miss_distance -220.0
loss[ 9 ]: 0.07883235264305993 miss_distance -218.4
loss[ 10 ]: 0.08072677302692002 miss_distance -218.4
loss[ 11 ]: 0.08213030463270103 miss_distance -217.20001
loss[ 12 ]: 0.08206500727096597 miss_distance -217.0
loss[ 13 ]: 0.07907577014243942 miss_distance -217.8
loss[ 14 ]: 0.07897956977755254 miss_distance -218.1
loss[ 15 ]: 0.07811987288461048 miss_distance -218.1
loss[ 16 ]: 0.07743458051315354 miss_distance -218.0
loss[ 17 ]: 0.07700261899373773 miss_distance -221.2
loss[ 18 ]: 0.07147371723990827 miss_distance

loss[ 155 ]: 0.12075925806612044 miss_distance -208.6
loss[ 156 ]: 0.11790410690427378 miss_distance -194.0
loss[ 157 ]: 0.10873492205566153 miss_distance -190.40001
loss[ 158 ]: 0.10553041792647215 miss_distance -189.5
loss[ 159 ]: 0.1056206655459575 miss_distance -191.09999
loss[ 160 ]: 0.10600859423525757 miss_distance -192.0
loss[ 161 ]: 0.08888378461484102 miss_distance -192.0
loss[ 162 ]: 0.08082224432084122 miss_distance -191.0
loss[ 163 ]: 0.08008226012928385 miss_distance -191.0
loss[ 164 ]: 0.08159295657170115 miss_distance -194.0
loss[ 165 ]: 0.07890690813779892 miss_distance -197.0
loss[ 166 ]: 0.07805803331666784 miss_distance -197.0
loss[ 167 ]: 0.08053281550557019 miss_distance -197.0
loss[ 168 ]: 0.08310043243187232 miss_distance -198.0
loss[ 169 ]: 0.091354671993736 miss_distance -197.0
loss[ 170 ]: 0.10307621601873275 miss_distance -197.70001
loss[ 171 ]: 0.10699779967583829 miss_distance -201.29999
loss[ 172 ]: 0.10641683768608462 miss_distance -198.0
loss[ 173 ]: 0.

loss[ 320 ]: 0.06875825708243817 miss_distance -210.00002
loss[ 321 ]: 0.07699058739365232 miss_distance -204.40001
loss[ 322 ]: 0.0855457201022946 miss_distance -213.1
loss[ 323 ]: 0.08513758319041292 miss_distance -220.5
loss[ 324 ]: 0.07977404425038809 miss_distance -212.0
loss[ 325 ]: 0.08103871148744526 miss_distance -236.2
loss[ 326 ]: 0.08085418278634518 miss_distance -265.6
loss[ 327 ]: 0.07142407530274193 miss_distance -279.2
loss[ 328 ]: 0.06696981117001541 miss_distance -270.0
loss[ 329 ]: 0.062920731042409 miss_distance -284.19998
loss[ 330 ]: 0.059487515120820615 miss_distance -272.9
loss[ 331 ]: 0.05601209835924675 miss_distance -272.90002
loss[ 332 ]: 0.047978905457931584 miss_distance -255.0
loss[ 333 ]: 0.03769995868212367 miss_distance -223.8
loss[ 334 ]: 0.025661831849475507 miss_distance -193.40001
loss[ 335 ]: 0.021345502553801965 miss_distance -200.79999
loss[ 336 ]: 0.01736741800329152 miss_distance -204.0
loss[ 337 ]: 0.01916296485685886 miss_distance -193.8
los

loss[ 488 ]: 0.041351801816186896 miss_distance -223.0
loss[ 489 ]: 0.033584351786879754 miss_distance -229.4
loss[ 490 ]: 0.02490406768605736 miss_distance -241.29999
loss[ 491 ]: 0.02694618634144441 miss_distance -252.3
loss[ 492 ]: 0.02812134571483793 miss_distance -255.0
loss[ 493 ]: 0.027895782132281017 miss_distance -250.6
loss[ 494 ]: 0.02328338736985202 miss_distance -247.2
loss[ 495 ]: 0.020791255727894167 miss_distance -232.20001
loss[ 496 ]: 0.02067365695679911 miss_distance -224.0
loss[ 497 ]: 0.024556707586694433 miss_distance -224.4
loss[ 498 ]: 0.027986442017475136 miss_distance -223.79999
loss[ 499 ]: 0.030574292537994863 miss_distance -219.8
loss[ 500 ]: 0.030830692509977286 miss_distance -227.0
loss[ 501 ]: 0.033666543048801706 miss_distance -235.6
loss[ 502 ]: 0.03232307292983577 miss_distance -240.1
loss[ 503 ]: 0.02693245851660273 miss_distance -239.29999
loss[ 504 ]: 0.023435522060919173 miss_distance -244.0
loss[ 505 ]: 0.022756907601375075 miss_distance -235.200

loss[ 649 ]: 0.0603589837254113 miss_distance -260.8
loss[ 650 ]: 0.05955371333765331 miss_distance -263.8
loss[ 651 ]: 0.05913945400907865 miss_distance -265.4
loss[ 652 ]: 0.059208985220281285 miss_distance -257.0
loss[ 653 ]: 0.059034746818373396 miss_distance -262.6
loss[ 654 ]: 0.05635910815780898 miss_distance -258.4
loss[ 655 ]: 0.05185612722082823 miss_distance -257.0
loss[ 656 ]: 0.04749915541433321 miss_distance -251.0
loss[ 657 ]: 0.037653736484661984 miss_distance -252.80002
loss[ 658 ]: 0.024491005401924133 miss_distance -235.69998
loss[ 659 ]: 0.018729514680779442 miss_distance -225.5
loss[ 660 ]: 0.016961381762520645 miss_distance -227.0
loss[ 661 ]: 0.015002894265918575 miss_distance -201.4
loss[ 662 ]: 0.014742795542312693 miss_distance -188.59999
loss[ 663 ]: 0.014806120163136443 miss_distance -184.0
loss[ 664 ]: 0.014159180708960906 miss_distance -185.0
loss[ 665 ]: 0.016462314120333627 miss_distance -158.2
loss[ 666 ]: 0.014350657728752209 miss_distance -158.9
loss[

loss[ 800 ]: 0.05281671171175253 miss_distance -284.0
loss[ 801 ]: 0.051892122481262175 miss_distance -287.2
loss[ 802 ]: 0.06502176073294257 miss_distance -301.7
loss[ 803 ]: 0.060992838173907826 miss_distance -293.1
loss[ 804 ]: 0.05980694156495581 miss_distance -295.0
loss[ 805 ]: 0.054607964397943486 miss_distance -278.40002
loss[ 806 ]: 0.05382260918355709 miss_distance -268.5
loss[ 807 ]: 0.05274129953089616 miss_distance -280.1
loss[ 808 ]: 0.05287182172495441 miss_distance -279.0
loss[ 809 ]: 0.04796194808115363 miss_distance -253.0
loss[ 810 ]: 0.0454774984115149 miss_distance -223.9
loss[ 811 ]: 0.045240389636628395 miss_distance -206.09999
loss[ 812 ]: 0.04712201420460964 miss_distance -207.0
loss[ 813 ]: 0.04099241810141777 miss_distance -200.8
loss[ 814 ]: 0.01898853108741966 miss_distance -192.29999
loss[ 815 ]: 0.02015100620368802 miss_distance -203.9
loss[ 816 ]: 0.021860399816751513 miss_distance -201.0
loss[ 817 ]: 0.01959154887566444 miss_distance -197.6
loss[ 818 ]:

loss[ 960 ]: 0.05679266348388248 miss_distance -268.0
loss[ 961 ]: 0.07149903874025808 miss_distance -265.59998
loss[ 962 ]: 0.07505730612098492 miss_distance -275.2
loss[ 963 ]: 0.07422290904420266 miss_distance -295.2
loss[ 964 ]: 0.07300508660471938 miss_distance -304.0
loss[ 965 ]: 0.05865218240556159 miss_distance -258.40002
loss[ 966 ]: 0.04304532198109429 miss_distance -228.9
loss[ 967 ]: 0.0431858153236869 miss_distance -221.7
loss[ 968 ]: 0.041672197104848714 miss_distance -231.0
loss[ 969 ]: 0.0411699803225125 miss_distance -231.79999
loss[ 970 ]: 0.03933578367749228 miss_distance -227.0
loss[ 971 ]: 0.03530859046202247 miss_distance -217.2
loss[ 972 ]: 0.03116538712862854 miss_distance -216.99998
loss[ 973 ]: 0.03142615234107629 miss_distance -217.0
loss[ 974 ]: 0.03787007803971455 miss_distance -199.29999
loss[ 975 ]: 0.04010759178718143 miss_distance -177.7
loss[ 976 ]: 0.039324598149974015 miss_distance -167.0
loss[ 977 ]: 0.05292040703935297 miss_distance -212.59999
loss

loss[ 1119 ]: 0.03218582531801586 miss_distance -249.40002
loss[ 1120 ]: 0.032122657819453615 miss_distance -250.0
loss[ 1121 ]: 0.028647798966275045 miss_distance -225.20001
loss[ 1122 ]: 0.03216900634602007 miss_distance -242.90001
loss[ 1123 ]: 0.03295422404601627 miss_distance -254.90001
loss[ 1124 ]: 0.030319265208932154 miss_distance -263.0
loss[ 1125 ]: 0.03053237133913899 miss_distance -255.80002
loss[ 1126 ]: 0.0219118336251078 miss_distance -250.2
loss[ 1127 ]: 0.018226879815251576 miss_distance -254.0
loss[ 1128 ]: 0.0173465967136407 miss_distance -266.0
loss[ 1129 ]: 0.01885136070038868 miss_distance -234.40001
loss[ 1130 ]: 0.01793627179320564 miss_distance -231.1
loss[ 1131 ]: 0.019382084670962623 miss_distance -254.5
loss[ 1132 ]: 0.02274756890494991 miss_distance -278.0
loss[ 1133 ]: 0.02814720526067182 miss_distance -299.2
loss[ 1134 ]: 0.02410166443833027 miss_distance -306.6
loss[ 1135 ]: 0.023041629037053014 miss_distance -308.2
loss[ 1136 ]: 0.02471988594958326 mis

loss[ 1279 ]: 0.012191937531367762 miss_distance -226.29999
loss[ 1280 ]: 0.012964462194830832 miss_distance -214.0
loss[ 1281 ]: 0.014875923387037703 miss_distance -201.20001
loss[ 1282 ]: 0.013978960919633123 miss_distance -191.4
loss[ 1283 ]: 0.013666187581581874 miss_distance -191.4
loss[ 1284 ]: 0.014139554464557854 miss_distance -182.0
loss[ 1285 ]: 0.015910846901961845 miss_distance -166.79999
loss[ 1286 ]: 0.018271032100039494 miss_distance -162.0
loss[ 1287 ]: 0.018709184576409355 miss_distance -156.2
loss[ 1288 ]: 0.01687559656232598 miss_distance -147.0
loss[ 1289 ]: 0.017155615730954487 miss_distance -150.0
loss[ 1290 ]: 0.01735868594355496 miss_distance -146.4
loss[ 1291 ]: 0.017512057673644825 miss_distance -156.6
loss[ 1292 ]: 0.016954216439316182 miss_distance -172.0
loss[ 1293 ]: 0.012248528457134464 miss_distance -168.79999
loss[ 1294 ]: 0.011700197612049674 miss_distance -183.59999
loss[ 1295 ]: 0.010922833880938839 miss_distance -185.59999
loss[ 1296 ]: 0.0101112598

loss[ 1426 ]: 0.020931056175595455 miss_distance -255.0
loss[ 1427 ]: 0.02689319961547197 miss_distance -279.2
loss[ 1428 ]: 0.028464364189101105 miss_distance -272.0
loss[ 1429 ]: 0.02639452917646309 miss_distance -255.0
loss[ 1430 ]: 0.02789158861316146 miss_distance -241.8
loss[ 1431 ]: 0.033763454176716196 miss_distance -254.19998
loss[ 1432 ]: 0.026974603928964884 miss_distance -238.0
loss[ 1433 ]: 0.02474461025014718 miss_distance -243.59999
loss[ 1434 ]: 0.02583606112587178 miss_distance -252.20001
loss[ 1435 ]: 0.02764328431557365 miss_distance -252.20001
loss[ 1436 ]: 0.022418545238431155 miss_distance -244.0
loss[ 1437 ]: 0.0248119541124724 miss_distance -269.4
loss[ 1438 ]: 0.019121223569672077 miss_distance -267.6
loss[ 1439 ]: 0.013554966351682423 miss_distance -264.0
loss[ 1440 ]: 0.007382754234947681 miss_distance -263.0
loss[ 1441 ]: 0.011450461840651505 miss_distance -287.2
loss[ 1442 ]: 0.01191288554226531 miss_distance -304.8
loss[ 1443 ]: 0.009548890887148949 miss_d

loss[ 1580 ]: 0.006806894455158404 miss_distance -262.0
loss[ 1581 ]: 0.007495099093361394 miss_distance -247.79999
loss[ 1582 ]: 0.006489092292421288 miss_distance -236.69998
loss[ 1583 ]: 0.007027680901983996 miss_distance -234.5
loss[ 1584 ]: 0.008724818309382203 miss_distance -232.0
loss[ 1585 ]: 0.009355763469015097 miss_distance -225.4
loss[ 1586 ]: 0.008862056064706591 miss_distance -232.9
loss[ 1587 ]: 0.008879981381785987 miss_distance -251.69998
loss[ 1588 ]: 0.008914941218380375 miss_distance -245.0
loss[ 1589 ]: 0.008106269517171041 miss_distance -239.79999
loss[ 1590 ]: 0.00890936613752682 miss_distance -233.69998
loss[ 1591 ]: 0.009229488745846247 miss_distance -232.49998
loss[ 1592 ]: 0.006600687105409936 miss_distance -216.0
loss[ 1593 ]: 0.005977113851595958 miss_distance -194.4
loss[ 1594 ]: 0.00603128526079705 miss_distance -179.6
loss[ 1595 ]: 0.006167874746400508 miss_distance -173.0
loss[ 1596 ]: 0.0025209541231295974 miss_distance -174.0
loss[ 1597 ]: 0.006833392

loss[ 1725 ]: 0.010736716620552393 miss_distance -186.0
loss[ 1726 ]: 0.010504830796240405 miss_distance -177.20001
loss[ 1727 ]: 0.01235613678947246 miss_distance -176.79999
loss[ 1728 ]: 0.010676340301002951 miss_distance -199.0
loss[ 1729 ]: 0.009784234567228055 miss_distance -208.4
loss[ 1730 ]: 0.009202194285601121 miss_distance -218.5
loss[ 1731 ]: 0.008374523997058927 miss_distance -217.1
loss[ 1732 ]: 0.010129363833052856 miss_distance -245.99998
loss[ 1733 ]: 0.008081448638615754 miss_distance -241.99998
loss[ 1734 ]: 0.005229062326160786 miss_distance -249.99998
loss[ 1735 ]: 0.0034430907969138537 miss_distance -241.0
loss[ 1736 ]: 0.0047078031550856925 miss_distance -257.0
loss[ 1737 ]: 0.004063473925173672 miss_distance -258.0
loss[ 1738 ]: 0.00290940036372273 miss_distance -261.5
loss[ 1739 ]: 0.0019554583640145704 miss_distance -257.5
loss[ 1740 ]: 0.0021862550561115245 miss_distance -258.0
loss[ 1741 ]: 0.0013695057876949026 miss_distance -255.0
loss[ 1742 ]: 0.001023435

loss[ 1873 ]: 0.002769502714800176 miss_distance -286.8
loss[ 1874 ]: 0.003219168334322445 miss_distance -307.1
loss[ 1875 ]: 0.0032295455733932746 miss_distance -312.09998
loss[ 1876 ]: 0.0036994532768124975 miss_distance -316.0
loss[ 1877 ]: 0.0034217060844144442 miss_distance -324.2
loss[ 1878 ]: 0.0022464177029155505 miss_distance -304.7
loss[ 1879 ]: 0.0018911051407648706 miss_distance -297.09998
loss[ 1880 ]: 0.0015265447969255459 miss_distance -297.0
loss[ 1881 ]: 0.0017019608437572752 miss_distance -305.4
loss[ 1882 ]: 0.0020795532696699045 miss_distance -308.2
loss[ 1883 ]: 0.0026341470145519914 miss_distance -309.4
loss[ 1884 ]: 0.002489153669062018 miss_distance -313.0
loss[ 1885 ]: 0.0035228554436616964 miss_distance -283.40002
loss[ 1886 ]: 0.006164222493278456 miss_distance -261.8
loss[ 1887 ]: 0.006199440733545658 miss_distance -259.8
loss[ 1888 ]: 0.005913966544464272 miss_distance -265.0
loss[ 1889 ]: 0.006166805288500528 miss_distance -248.6
loss[ 1890 ]: 0.0065258232

loss[ 2031 ]: 0.0021610156424668988 miss_distance -291.4
loss[ 2032 ]: 0.0019281739503524491 miss_distance -280.0
loss[ 2033 ]: 0.0017676828637922337 miss_distance -287.2
loss[ 2034 ]: 0.001941262679602863 miss_distance -298.3
loss[ 2035 ]: 0.0019197498468895569 miss_distance -305.5
loss[ 2036 ]: 0.001902424832413561 miss_distance -296.0
loss[ 2037 ]: 0.0020659188961762408 miss_distance -281.6
loss[ 2038 ]: 0.003004959556589207 miss_distance -267.4
loss[ 2039 ]: 0.0027420550742203588 miss_distance -268.0
loss[ 2040 ]: 0.0022589355851905884 miss_distance -262.0
loss[ 2041 ]: 0.0020955903919985595 miss_distance -286.8
loss[ 2042 ]: 0.0023561656486122146 miss_distance -291.4
loss[ 2043 ]: 0.0025133410592295628 miss_distance -287.8
loss[ 2044 ]: 0.0022461876156093814 miss_distance -289.0
loss[ 2045 ]: 0.002080163423695324 miss_distance -253.8
loss[ 2046 ]: 0.0018478405410336687 miss_distance -223.8
loss[ 2047 ]: 0.0018020316002092436 miss_distance -209.4
loss[ 2048 ]: 0.001724196079302875 

loss[ 2194 ]: 0.002041169779685849 miss_distance -262.3
loss[ 2195 ]: 0.0019947627019595475 miss_distance -276.7
loss[ 2196 ]: 0.001873021213162488 miss_distance -276.0
loss[ 2197 ]: 0.0016623816306551773 miss_distance -301.6
loss[ 2198 ]: 0.0017264469376107978 miss_distance -320.5
loss[ 2199 ]: 0.001955121827892744 miss_distance -336.90002
loss[ 2200 ]: 0.001818085662785936 miss_distance -329.0
loss[ 2201 ]: 0.0021452407360554866 miss_distance -300.0
loss[ 2202 ]: 0.0021303529757298496 miss_distance -270.0
loss[ 2203 ]: 0.001896596354485054 miss_distance -260.0
loss[ 2204 ]: 0.0018071038392251928 miss_distance -255.0
loss[ 2205 ]: 0.001499971486321096 miss_distance -264.0
loss[ 2206 ]: 0.001066455068587106 miss_distance -237.7
loss[ 2207 ]: 0.0018807944898978721 miss_distance -224.3
loss[ 2208 ]: 0.00164516332648533 miss_distance -210.0
loss[ 2209 ]: 0.0019732597095053457 miss_distance -228.4
loss[ 2210 ]: 0.002676009110598852 miss_distance -239.5
loss[ 2211 ]: 0.0029773784037362408 m

loss[ 2352 ]: 0.002412019285679829 miss_distance -246.0
loss[ 2353 ]: 0.0017768772027420918 miss_distance -229.6
loss[ 2354 ]: 0.0015587061480470737 miss_distance -214.5
loss[ 2355 ]: 0.0014463446374325007 miss_distance -205.9
loss[ 2356 ]: 0.0008278420738605325 miss_distance -200.0
loss[ 2357 ]: 0.0006482335831047031 miss_distance -204.0
loss[ 2358 ]: 0.0005457926212894982 miss_distance -198.59999
loss[ 2359 ]: 0.0005013436997363763 miss_distance -191.40001
loss[ 2360 ]: 0.00038585961289525886 miss_distance -186.0
loss[ 2361 ]: 0.00027823621317078784 miss_distance -157.2
loss[ 2362 ]: 0.00014015715434164232 miss_distance -135.6
loss[ 2363 ]: 0.0002523578765802118 miss_distance -137.2
loss[ 2364 ]: 0.0003662601124995056 miss_distance -139.0
loss[ 2365 ]: 0.0004245596659466807 miss_distance -146.20001
loss[ 2366 ]: 0.000655630491820629 miss_distance -154.6
loss[ 2367 ]: 0.0008149364338129564 miss_distance -158.20001
loss[ 2368 ]: 0.0007968663973381136 miss_distance -165.0
loss[ 2369 ]: 

loss[ 2496 ]: 0.0005193878951216931 miss_distance -132.0
loss[ 2497 ]: 0.0004129894074269108 miss_distance -110.4
loss[ 2498 ]: 0.0005325078574786205 miss_distance -118.5
loss[ 2499 ]: 0.0006004681387412799 miss_distance -124.1
loss[ 2500 ]: 0.0005778860336611377 miss_distance -136.0
loss[ 2501 ]: 0.0004048375242005685 miss_distance -168.0
loss[ 2502 ]: 0.0005239113200372759 miss_distance -178.1
loss[ 2503 ]: 0.00037489537974344885 miss_distance -186.9
loss[ 2504 ]: 0.0003905577374419195 miss_distance -196.0
loss[ 2505 ]: 0.0006305729295697198 miss_distance -243.2
loss[ 2506 ]: 0.0006774391284328839 miss_distance -278.3
loss[ 2507 ]: 0.0007552548886943856 miss_distance -303.5
loss[ 2508 ]: 0.0010255089595989128 miss_distance -310.0
loss[ 2509 ]: 0.0008598884048820118 miss_distance -329.6
loss[ 2510 ]: 0.0012317561687775508 miss_distance -326.6
loss[ 2511 ]: 0.0012134964905798126 miss_distance -314.8
loss[ 2512 ]: 0.001405326825424043 miss_distance -302.0
loss[ 2513 ]: 0.001266263812724

loss[ 2649 ]: 0.000541207193034348 miss_distance -267.0
loss[ 2650 ]: 0.0005521495642359913 miss_distance -261.6
loss[ 2651 ]: 0.0006152861538639427 miss_distance -254.40002
loss[ 2652 ]: 0.0007290053413095456 miss_distance -245.99998
loss[ 2653 ]: 0.0006364949327783508 miss_distance -220.2
loss[ 2654 ]: 0.000655264114494417 miss_distance -222.90001
loss[ 2655 ]: 0.0006786086178363868 miss_distance -240.9
loss[ 2656 ]: 0.0007370542698464944 miss_distance -246.99998
loss[ 2657 ]: 0.0005604624174390486 miss_distance -278.8
loss[ 2658 ]: 0.0006665012554111492 miss_distance -297.7
loss[ 2659 ]: 0.0007774659570671774 miss_distance -293.5
loss[ 2660 ]: 0.0007347225624259509 miss_distance -286.0
loss[ 2661 ]: 0.000811653520979623 miss_distance -267.40002
loss[ 2662 ]: 0.0007389505823903125 miss_distance -253.6
loss[ 2663 ]: 0.000648405666376606 miss_distance -249.99998
loss[ 2664 ]: 0.0004178713645670255 miss_distance -253.0
loss[ 2665 ]: 0.0002934773563911034 miss_distance -256.19998
loss[ 2

loss[ 2813 ]: 0.0005895054147750448 miss_distance -266.4
loss[ 2814 ]: 0.00044251031563791757 miss_distance -274.2
loss[ 2815 ]: 0.00038695249683530606 miss_distance -263.40002
loss[ 2816 ]: 0.00038224457611683307 miss_distance -258.0
loss[ 2817 ]: 0.0004260960381933293 miss_distance -236.4
loss[ 2818 ]: 0.0007404956629368182 miss_distance -250.20001
loss[ 2819 ]: 0.0009237317081633462 miss_distance -259.40002
loss[ 2820 ]: 0.0006287824966465055 miss_distance -261.0
loss[ 2821 ]: 0.00038300806253529547 miss_distance -236.4
loss[ 2822 ]: 0.0002847305741111005 miss_distance -222.9
loss[ 2823 ]: 0.0002602213606411475 miss_distance -215.7
loss[ 2824 ]: 0.00033629387287980217 miss_distance -213.0
loss[ 2825 ]: 0.0003595397359218012 miss_distance -241.8
loss[ 2826 ]: 0.000397345614357353 miss_distance -263.4
loss[ 2827 ]: 0.0004451328328112289 miss_distance -277.8
loss[ 2828 ]: 0.0005949102261734264 miss_distance -283.0
loss[ 2829 ]: 0.0006483828278190317 miss_distance -313.8
loss[ 2830 ]: 0

loss[ 2956 ]: 0.0008654394260163525 miss_distance -259.0
loss[ 2957 ]: 0.0007226934645641247 miss_distance -244.59999
loss[ 2958 ]: 0.0007350672488489371 miss_distance -228.4
loss[ 2959 ]: 0.0006612839152370996 miss_distance -213.0
loss[ 2960 ]: 0.0007308774218894173 miss_distance -204.0
loss[ 2961 ]: 0.0006890544407939284 miss_distance -233.79999
loss[ 2962 ]: 0.0007622633478871019 miss_distance -274.0
loss[ 2963 ]: 0.0007568842290873516 miss_distance -277.2
loss[ 2964 ]: 0.0006110039121345508 miss_distance -283.0
loss[ 2965 ]: 0.0007006901853949277 miss_distance -280.0
loss[ 2966 ]: 0.0005785178733759976 miss_distance -274.6
loss[ 2967 ]: 0.0007024173461375136 miss_distance -288.40002
loss[ 2968 ]: 0.0005234313670201617 miss_distance -295.0
loss[ 2969 ]: 0.0007220595809526533 miss_distance -298.2
loss[ 2970 ]: 0.0007001786653544772 miss_distance -314.4
loss[ 2971 ]: 0.0005500154386205832 miss_distance -335.4
loss[ 2972 ]: 0.0005447237678340821 miss_distance -348.0
loss[ 2973 ]: 0.000

loss[ 3113 ]: 0.0003759792154416243 miss_distance -295.0
loss[ 3114 ]: 0.0003522411765519227 miss_distance -284.2
loss[ 3115 ]: 0.00035777651390488606 miss_distance -269.8
loss[ 3116 ]: 0.0005144249154674784 miss_distance -257.0
loss[ 3117 ]: 0.0006080531136649635 miss_distance -236.40001
loss[ 3118 ]: 0.0005156804206127195 miss_distance -244.5
loss[ 3119 ]: 0.00048157064532741077 miss_distance -248.1
loss[ 3120 ]: 0.0005166212591564992 miss_distance -247.0
loss[ 3121 ]: 0.0005029462762332964 miss_distance -249.0
loss[ 3122 ]: 0.00044197733605391286 miss_distance -240.9
loss[ 3123 ]: 0.0005447692749238169 miss_distance -234.1
loss[ 3124 ]: 0.00038759290115699573 miss_distance -223.0
loss[ 3125 ]: 0.0005288343253159662 miss_distance -215.8
loss[ 3126 ]: 0.0005115794633278937 miss_distance -237.4
loss[ 3127 ]: 0.0005098278733157632 miss_distance -251.79999
loss[ 3128 ]: 0.00040502063149730667 miss_distance -259.0
loss[ 3129 ]: 0.0004169631937132524 miss_distance -251.79999
loss[ 3130 ]: 

loss[ 3272 ]: 0.00034591267503733986 miss_distance -303.0
loss[ 3273 ]: 0.0002432811694011043 miss_distance -295.8
loss[ 3274 ]: 0.00024936117557255424 miss_distance -293.1
loss[ 3275 ]: 0.00024097990523657558 miss_distance -293.1
loss[ 3276 ]: 0.0002466833924682219 miss_distance -285.0
loss[ 3277 ]: 0.00028070099768948386 miss_distance -293.2
loss[ 3278 ]: 0.0003069347022310768 miss_distance -287.8
loss[ 3279 ]: 0.00031412542004520224 miss_distance -277.0
loss[ 3280 ]: 0.0004169665777688645 miss_distance -280.0
loss[ 3281 ]: 0.00040654170344389825 miss_distance -263.59998
loss[ 3282 ]: 0.00034073217694293557 miss_distance -250.1
loss[ 3283 ]: 0.00033993504078964264 miss_distance -239.29999
loss[ 3284 ]: 0.00034723831692292257 miss_distance -240.0
loss[ 3285 ]: 0.00032594827545757966 miss_distance -247.20001
loss[ 3286 ]: 0.00025719357019111244 miss_distance -252.6
loss[ 3287 ]: 0.00023592519771245137 miss_distance -256.2
loss[ 3288 ]: 0.0002413060477902597 miss_distance -258.0
loss[ 3

loss[ 3422 ]: 0.00034992455752959095 miss_distance -299.4
loss[ 3423 ]: 0.00025895010159130344 miss_distance -295.8
loss[ 3424 ]: 0.00041359099254401446 miss_distance -286.0
loss[ 3425 ]: 0.0004233882349157194 miss_distance -278.8
loss[ 3426 ]: 0.0007500470804874278 miss_distance -244.0
loss[ 3427 ]: 0.0007023468612760719 miss_distance -251.2
loss[ 3428 ]: 0.0006295587949782337 miss_distance -252.99998
loss[ 3429 ]: 0.0005457276754497831 miss_distance -253.0
loss[ 3430 ]: 0.0005263332961147283 miss_distance -252.0
loss[ 3431 ]: 0.0005162478605328994 miss_distance -252.0
loss[ 3432 ]: 0.0004853069665584575 miss_distance -251.99998
loss[ 3433 ]: 0.00047868396066065946 miss_distance -252.0
loss[ 3434 ]: 0.0005081691114229289 miss_distance -257.40002
loss[ 3435 ]: 0.0004703026874806706 miss_distance -264.6
loss[ 3436 ]: 0.0006032333600157529 miss_distance -269.0
loss[ 3437 ]: 0.0006260038084779337 miss_distance -259.8
loss[ 3438 ]: 0.0007715471499566332 miss_distance -287.8
loss[ 3439 ]: 0

loss[ 3576 ]: 0.00028096449704014095 miss_distance -347.0
loss[ 3577 ]: 0.0003950798775848467 miss_distance -355.19998
loss[ 3578 ]: 0.0005115149705889163 miss_distance -356.5
loss[ 3579 ]: 0.0004901315576039275 miss_distance -349.3
loss[ 3580 ]: 0.0002466967480810204 miss_distance -339.0
loss[ 3581 ]: 0.0002835688475503045 miss_distance -303.0
loss[ 3582 ]: 0.00025582741629164745 miss_distance -294.90002
loss[ 3583 ]: 0.00021463871597054754 miss_distance -284.1
loss[ 3584 ]: 0.00019382133803447338 miss_distance -276.0
loss[ 3585 ]: 0.00018446610085351252 miss_distance -232.8
loss[ 3586 ]: 0.00038607938364828756 miss_distance -206.09999
loss[ 3587 ]: 0.0004147251924578571 miss_distance -206.1
loss[ 3588 ]: 0.00046085231011320555 miss_distance -216.0
loss[ 3589 ]: 0.00036348513024671763 miss_distance -223.2
loss[ 3590 ]: 0.0003447407407155575 miss_distance -225.9
loss[ 3591 ]: 0.0003217642401562063 miss_distance -225.9
loss[ 3592 ]: 0.0003603095532266089 miss_distance -224.99998
loss[ 3

loss[ 3730 ]: 0.0003555763315522241 miss_distance -249.90001
loss[ 3731 ]: 0.0003492447876861692 miss_distance -235.5
loss[ 3732 ]: 0.0003828782955175747 miss_distance -231.0
loss[ 3733 ]: 0.0003968781375016934 miss_distance -223.8
loss[ 3734 ]: 0.0006007146835358742 miss_distance -220.79999
loss[ 3735 ]: 0.0006247932014014808 miss_distance -224.4
loss[ 3736 ]: 0.0005895556502908605 miss_distance -230.99998
loss[ 3737 ]: 0.0005175543414918084 miss_distance -216.59999
loss[ 3738 ]: 0.00045686515182225056 miss_distance -203.1
loss[ 3739 ]: 0.0004737393123529873 miss_distance -213.3
loss[ 3740 ]: 0.0004512734171649118 miss_distance -216.0
loss[ 3741 ]: 0.0004973383188293492 miss_distance -223.20001
loss[ 3742 ]: 0.0003545319296323691 miss_distance -217.5
loss[ 3743 ]: 0.0003688344741078383 miss_distance -228.29999
loss[ 3744 ]: 0.00037304434647566055 miss_distance -230.0
loss[ 3745 ]: 0.00042833765356124764 miss_distance -231.0
loss[ 3746 ]: 0.00048115076060866797 miss_distance -228.29999

loss[ 3879 ]: 0.0002444395384677835 miss_distance -298.5
loss[ 3880 ]: 0.0003012482462017691 miss_distance -302.0
loss[ 3881 ]: 0.00025570009768454197 miss_distance -317.4
loss[ 3882 ]: 0.00033518891012751295 miss_distance -300.9
loss[ 3883 ]: 0.00026032668231634596 miss_distance -296.69998
loss[ 3884 ]: 0.0004428308322410445 miss_distance -295.0
loss[ 3885 ]: 0.0003609577237202753 miss_distance -287.8
loss[ 3886 ]: 0.00025618758194934175 miss_distance -279.69998
loss[ 3887 ]: 0.00028648298552142875 miss_distance -271.5
loss[ 3888 ]: 0.00022588294012204215 miss_distance -267.0
loss[ 3889 ]: 0.0004368054341645179 miss_distance -245.4
loss[ 3890 ]: 0.00038472799046943376 miss_distance -240.0
loss[ 3891 ]: 0.00038000047053758255 miss_distance -243.6
loss[ 3892 ]: 0.00026973182649571556 miss_distance -241.0
loss[ 3893 ]: 0.00035251436895277714 miss_distance -241.0
loss[ 3894 ]: 0.0004910087150791615 miss_distance -246.4
loss[ 3895 ]: 0.0004546532197347902 miss_distance -253.6
loss[ 3896 ]:

loss[ 4038 ]: 8.215138918520837e-05 miss_distance -219.29999
loss[ 4039 ]: 8.265431805441067e-05 miss_distance -244.5
loss[ 4040 ]: 0.00011245826766109176 miss_distance -240.0
loss[ 4041 ]: 9.808737316594858e-05 miss_distance -225.6
loss[ 4042 ]: 0.00012551030290886263 miss_distance -212.1
loss[ 4043 ]: 0.0001323587990900686 miss_distance -219.3
loss[ 4044 ]: 0.000120139344400171 miss_distance -222.0
loss[ 4045 ]: 9.84110477551565e-05 miss_distance -193.20001
loss[ 4046 ]: 0.00019550503611203527 miss_distance -177.3
loss[ 4047 ]: 0.00020761472042343503 miss_distance -181.5
loss[ 4048 ]: 0.00021238991995636825 miss_distance -186.0
loss[ 4049 ]: 0.00016894504062649426 miss_distance -207.6
loss[ 4050 ]: 0.00018050762125587297 miss_distance -194.1
loss[ 4051 ]: 0.00019564483512396813 miss_distance -183.3
loss[ 4052 ]: 0.0002018047902375843 miss_distance -186.0
loss[ 4053 ]: 0.00015463801084174508 miss_distance -229.2
loss[ 4054 ]: 0.0001597929613531391 miss_distance -261.6
loss[ 4055 ]: 0.

loss[ 4188 ]: 0.00025656157817682 miss_distance -168.0
loss[ 4189 ]: 0.0002416694265465026 miss_distance -189.6
loss[ 4190 ]: 0.00031101183354746134 miss_distance -205.79999
loss[ 4191 ]: 0.0002849240423126532 miss_distance -216.6
loss[ 4192 ]: 0.0002762317061038999 miss_distance -220.99998
loss[ 4193 ]: 0.00023406230396446105 miss_distance -243.59999
loss[ 4194 ]: 0.00023045257301453079 miss_distance -254.40001
loss[ 4195 ]: 0.00019390955461915649 miss_distance -276.0
loss[ 4196 ]: 0.0001448928936011192 miss_distance -276.0
loss[ 4197 ]: 0.00015106800781880482 miss_distance -268.8
loss[ 4198 ]: 0.0001589781334352222 miss_distance -274.2
loss[ 4199 ]: 0.0001485837634515452 miss_distance -285.0
loss[ 4200 ]: 0.000146141614964594 miss_distance -285.0
loss[ 4201 ]: 0.000135480602708139 miss_distance -299.4
loss[ 4202 ]: 0.00015358426390600332 miss_distance -283.19998
loss[ 4203 ]: 0.00019955170805306248 miss_distance -272.40002
loss[ 4204 ]: 0.00018682735728020624 miss_distance -267.0
los

loss[ 4342 ]: 0.0005850837447848018 miss_distance -216.0
loss[ 4343 ]: 0.0006374979879189796 miss_distance -207.19998
loss[ 4344 ]: 0.0005139460747460006 miss_distance -195.0
loss[ 4345 ]: 0.0003830953525006126 miss_distance -195.0
loss[ 4346 ]: 0.0004441643170239881 miss_distance -206.1
loss[ 4347 ]: 0.000445562078111632 miss_distance -216.9
loss[ 4348 ]: 0.0003870510953211416 miss_distance -222.0
loss[ 4349 ]: 0.00042186584072735015 miss_distance -265.2
loss[ 4350 ]: 0.0002906028101140004 miss_distance -251.7
loss[ 4351 ]: 0.0002570729051306878 miss_distance -248.1
loss[ 4352 ]: 0.00028175718117033296 miss_distance -249.0
loss[ 4353 ]: 0.00026623058442654937 miss_distance -263.4
loss[ 4354 ]: 0.0002543774753915564 miss_distance -271.5
loss[ 4355 ]: 0.0002594699644517613 miss_distance -275.09998
loss[ 4356 ]: 0.00015108576330830005 miss_distance -276.0
loss[ 4357 ]: 0.00015372593435491696 miss_distance -312.0
loss[ 4358 ]: 0.00021859330427484645 miss_distance -330.9
loss[ 4359 ]: 0.00

loss[ 4497 ]: 0.00020658865386048836 miss_distance -295.8
loss[ 4498 ]: 0.00021093447914793568 miss_distance -285.0
loss[ 4499 ]: 0.00022402427594940633 miss_distance -274.2
loss[ 4500 ]: 0.00023074546660117404 miss_distance -267.0
loss[ 4501 ]: 0.00022476836334307646 miss_distance -303.0
loss[ 4502 ]: 0.00022509700073950172 miss_distance -273.3
loss[ 4503 ]: 0.00021851608744816498 miss_distance -251.70001
loss[ 4504 ]: 0.00019305861880982542 miss_distance -249.0
loss[ 4505 ]: 0.00016942496427622907 miss_distance -234.6
loss[ 4506 ]: 0.00019480151294223863 miss_distance -223.8
loss[ 4507 ]: 0.0002159375621341707 miss_distance -216.6
loss[ 4508 ]: 0.000181457253416794 miss_distance -213.0
loss[ 4509 ]: 0.00018503305906985556 miss_distance -198.6
loss[ 4510 ]: 0.00027853056438228513 miss_distance -193.20001
loss[ 4511 ]: 0.00026467066095037207 miss_distance -193.2
loss[ 4512 ]: 0.00024845888549463835 miss_distance -195.0
loss[ 4513 ]: 0.00024875487870916485 miss_distance -137.4
loss[ 451

### Visualize

In [ ]:
fig = plt.figure()
im = plt.imshow(momentum_object.render(), animated=True)
def updatefig(*args):
    position = momentum_object.get_state_action().reshape(1,4)
    predict_position = encoder(standardize_state(position)).detach()
    _predict_position = torch.round(denormalize_state(predict_position).detach())[0]
    momentum_object.step()
    im.set_array(momentum_object.render(_predict_position))
ani = FuncAnimation(fig, updatefig, interval=500, frames=100, blit=True)
plt.show()
updatefig()

In [109]:
memory.step()
position = memory.states_actions[0].reshape(1,4)
num_next_step = num_step_per_action - memory.current_step
predict_position = encoder(standardize_state(position)).detach()
predict_position = predict_position.repeat((num_next_step, 1))
predict_position_delta_time = torch.cat((predict_position, 
                               torch.arange(num_next_step, device=device).reshape(-1,1)), 
                               axis=1)
torch.round(denormalize_state(decoder(predict_position_delta_time)).detach())

tensor([[8., 3.]], device='cuda:0', dtype=torch.float64)