# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[43, 67],
       [75, 85],
       [57, 99],
       [51, 13],
       [58, 77],
       [41, 76],
       [ 2, 65],
       [71, 38],
       [63, 15],
       [ 0, 20]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

/Users/epinyoanun/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[ 0.57333333,  0.62790698],
       [ 1.        ,  0.8372093 ],
       [ 0.76      ,  1.        ],
       [ 0.68      ,  0.        ],
       [ 0.77333333,  0.74418605],
       [ 0.54666667,  0.73255814],
       [ 0.02666667,  0.60465116],
       [ 0.94666667,  0.29069767],
       [ 0.84      ,  0.02325581],
       [ 0.        ,  0.08139535]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)
# but normally we fit 'train data'
#  ```scaler_model.fit(data)```
# then transform 'test data'
#  ```scaler_model.transform(data)```
# so the 

/Users/epinyoanun/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[ 0.57333333,  0.62790698],
       [ 1.        ,  0.8372093 ],
       [ 0.76      ,  1.        ],
       [ 0.68      ,  0.        ],
       [ 0.77333333,  0.74418605],
       [ 0.54666667,  0.73255814],
       [ 0.02666667,  0.60465116],
       [ 0.94666667,  0.29069767],
       [ 0.84      ,  0.02325581],
       [ 0.        ,  0.08139535]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(
    data=np.random.randint(0,101,(50,4)),
    columns=['f1','f2','f3','label']
)

In [12]:
data.head()

f1  f2  f3  label
0   7   7   2     19
1  86  48  97     21
2  58  52  78     66
3  60  11  61     66
4  56  28   7     18

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, 
X_test, 
y_train, 
y_test = train_test_split(x,y,test_size=0.3,random_state=101)
# random_state :: random seed

NameError: name 'X_train' is not defined

In [ ]:
X_train.shape

In [ ]:
X_test.shape

In [ ]:
y_train.shape

In [ ]:
y_test.shape

## Great Job!